INSERT INTO clientes(id, name, apellido) VALUES(1, 'Jesus', 'Camacaro');
INSERT INTO clientes(id, name, apellido) VALUES(2, 'Marellys', 'Ruiz');
INSERT INTO clientes(id, name, apellido) VALUES(3, 'Danny', 'Camacaro');
INSERT INTO clientes(id, name, apellido) VALUES(4, 'Emmanuel', 'Camacaro');
INSERT INTO clientes(id, name, apellido) VALUES(5, 'luis', 'Rodriguez');
INSERT INTO clientes(id, name, apellido) VALUES(6, 'Erick', 'Camacaro');
INSERT INTO clientes(id, name, apellido) VALUES(7, 'Jose', 'Mota');

INSERT INTO facturas(id, producto, clientes_id) VALUES(1, 'Xiaomi', 5);
INSERT INTO facturas(id, producto, clientes_id) VALUES(2, 'Blackberry', 6);
INSERT INTO facturas(id, producto, clientes_id) VALUES(3, 'Samsung', 4);
INSERT INTO facturas(id, producto, clientes_id) VALUES(4, 'Iphone', 7);
INSERT INTO facturas(id, producto, clientes_id) VALUES(5, 'Samsung', 6);
INSERT INTO facturas(id, producto, clientes_id) VALUES(6, 'Zte', 1);
INSERT INTO facturas(id, producto, clientes_id) VALUES(7, 'Iphone', 1);
INSERT INTO facturas(id, producto, clientes_id) VALUES(8, 'Samsung', 2);
INSERT INTO facturas(id, producto, clientes_id) VALUES(9, 'Iphone', 2);
INSERT INTO facturas(id, producto, clientes_id) VALUES(10, 'Samsung', 3);
INSERT INTO facturas(id, producto, clientes_id) VALUES(11, 'Motorola', 3);